kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
  labels: 
     app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-react-app
          image: sagark24/nodeapplication
          ports:
            - containerPort: 80
    
---

kind: Service
apiVersion: v1
metadata:
  name: my-react-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: my-app

